package com.example.myshopping.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

import static com.fasterxml.jackson.annotation.JsonFormat.DEFAULT_TIMEZONE;

public class Carousel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.carousel_id
     *
     * @mbggenerated
     */
    private Integer carouselId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.carousel_url
     *
     * @mbggenerated
     */
    private String carouselUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.redirect_url
     *
     * @mbggenerated
     */
    private String redirectUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.carousel_rank
     *
     * @mbggenerated
     */
    private Integer carouselRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.is_deleted
     *
     * @mbggenerated
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.create_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "UTC+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.create_user
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.update_user
     *
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.carousel_id
     *
     * @return the value of carousel.carousel_id
     *
     * @mbggenerated
     */
    public Integer getCarouselId() {
        return carouselId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.carousel_id
     *
     * @param carouselId the value for carousel.carousel_id
     *
     * @mbggenerated
     */
    public void setCarouselId(Integer carouselId) {
        this.carouselId = carouselId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.carousel_url
     *
     * @return the value of carousel.carousel_url
     *
     * @mbggenerated
     */
    public String getCarouselUrl() {
        return carouselUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.carousel_url
     *
     * @param carouselUrl the value for carousel.carousel_url
     *
     * @mbggenerated
     */
    public void setCarouselUrl(String carouselUrl) {
        this.carouselUrl = carouselUrl == null ? null : carouselUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.redirect_url
     *
     * @return the value of carousel.redirect_url
     *
     * @mbggenerated
     */
    public String getRedirectUrl() {
        return redirectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.redirect_url
     *
     * @param redirectUrl the value for carousel.redirect_url
     *
     * @mbggenerated
     */
    public void setRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl == null ? null : redirectUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.carousel_rank
     *
     * @return the value of carousel.carousel_rank
     *
     * @mbggenerated
     */
    public Integer getCarouselRank() {
        return carouselRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.carousel_rank
     *
     * @param carouselRank the value for carousel.carousel_rank
     *
     * @mbggenerated
     */
    public void setCarouselRank(Integer carouselRank) {
        this.carouselRank = carouselRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.is_deleted
     *
     * @return the value of carousel.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.is_deleted
     *
     * @param isDeleted the value for carousel.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.create_time
     *
     * @return the value of carousel.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.create_time
     *
     * @param createTime the value for carousel.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.create_user
     *
     * @return the value of carousel.create_user
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.create_user
     *
     * @param createUser the value for carousel.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.update_time
     *
     * @return the value of carousel.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.update_time
     *
     * @param updateTime the value for carousel.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.update_user
     *
     * @return the value of carousel.update_user
     *
     * @mbggenerated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.update_user
     *
     * @param updateUser the value for carousel.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }
}