package com.example.myshopping.dao;

import com.example.myshopping.entity.AdminUserToken;

public interface AdminUserTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_token
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long adminUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_token
     *
     * @mbggenerated
     */
    int insert(AdminUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_token
     *
     * @mbggenerated
     */
    int insertSelective(AdminUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_token
     *
     * @mbggenerated
     */
    AdminUserToken selectByPrimaryKey(Long adminUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdminUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminUserToken record);
}