package com.example.myshopping.dao;

import com.example.myshopping.entity.GoodsCategory;

public interface GoodsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated
     */
    int insert(GoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated
     */
    int insertSelective(GoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated
     */
    GoodsCategory selectByPrimaryKey(Long categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsCategory record);
}