package com.example.myshopping.dao;

import com.example.myshopping.entity.MallUserToken;

public interface MallUserTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbggenerated
     */
    int insert(MallUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbggenerated
     */
    int insertSelective(MallUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbggenerated
     */
    MallUserToken selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MallUserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MallUserToken record);
}