package com.example.myshopping.dao;

import com.example.myshopping.entity.OrderAddress;

public interface OrderAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_address
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_address
     *
     * @mbggenerated
     */
    int insert(OrderAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_address
     *
     * @mbggenerated
     */
    int insertSelective(OrderAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_address
     *
     * @mbggenerated
     */
    OrderAddress selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderAddress record);
}